# Generated by Django 5.0 on 2024-12-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicamento",
            name="precio",
            field=models.IntegerField(),
        ),
    ]
